# Generated by Django 6.0.6 on 2026-06-29 18:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('city', models.CharField(default='أبها', max_length=80)),
                ('location', models.CharField(max_length=160)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=40)),
                ('activity_type', models.CharField(blank=True, max_length=90)),
                ('audience', models.CharField(blank=True, max_length=140)),
                ('category', models.CharField(default='توعية', max_length=90)),
                ('map_url', models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url])),
                ('show_on_home', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فعالية صحية',
                'verbose_name_plural': 'الفعاليات الصحية',
                'ordering': ['order', 'date', 'time'],
            },
        ),
    ]
