# Generated by Django 6.0.6 on 2026-06-29 18:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'تفعيل وتعطيل الميزات',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='صيف وصحة - مساعد', max_length=120)),
                ('default_city', models.CharField(default='أبها', max_length=80)),
                ('support_phone', models.CharField(default='937', max_length=30)),
                ('emergency_phone', models.CharField(default='997', max_length=30)),
                ('achievement_stamp_target', models.PositiveIntegerField(default=4)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('offline_message', models.TextField(default='يمكنك متابعة تصفح الصفحات الأساسية، وسيتم تحديث البيانات عند عودة الاتصال.')),
            ],
            options={
                'verbose_name': 'إعداد عام',
                'verbose_name_plural': 'الإعدادات العامة',
            },
        ),
        migrations.CreateModel(
            name='HomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(default='صيف وصحة - مساعد', max_length=120)),
                ('tagline', models.CharField(default='مرشدك الصحي في صيف عسير', max_length=180)),
                ('intro', models.TextField(default='منصة صحية وتوعوية تساعد زائر عسير على اختيار خطة آمنة وموقع مناسب ومحتوى صحي موثوق.')),
                ('seasonal_alert', models.CharField(default='اشرب الماء على دفعات، وخذ استراحة في الظل عند المشي أو حضور الفعاليات.', max_length=240)),
                ('primary_button_label', models.CharField(default='ابدأ رحلتك الصحية', max_length=80)),
                ('call937_label', models.CharField(default='اتصال 937', max_length=80)),
                ('emergency997_label', models.CharField(default='طوارئ 997', max_length=80)),
                ('hero_image', models.CharField(blank=True, default='img/asir-hero.png', max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'إعداد الصفحة الرئيسية',
                'verbose_name_plural': 'إعدادات الصفحة الرئيسية',
            },
        ),
        migrations.CreateModel(
            name='HomeQuickButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=90)),
                ('url', models.CharField(max_length=220, validators=[core.validators.validate_safe_url])),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'زر سريع',
                'verbose_name_plural': 'الأزرار السريعة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SmartEntryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy_note', models.TextField(default='نستخدم معرف زائر عشوائي فقط لتحسين الرحلة واحتساب نقاط QR، ولا نجمع رقم الجوال أو موقعا دقيقا.')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'إعداد الدخول الذكي',
                'verbose_name_plural': 'إعدادات الدخول الذكي',
            },
        ),
    ]
