# Generated by Django 5.2.5 on 2026-06-30 06:56

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='events_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url]),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='hiking_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url]),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='hotels_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url]),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='landmarks_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url]),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='parks_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url]),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='restaurants_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url]),
        ),
    ]
