# Generated by Django 5.2.5 on 2026-06-30 06:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generalsettings_events_map_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='events_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url], verbose_name='رابط الفعاليات في خريطة عسير'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='hiking_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url], verbose_name='رابط الهايكنج في خريطة عسير'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='hotels_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url], verbose_name='رابط الفنادق في خريطة عسير'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='landmarks_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url], verbose_name='رابط المعالم في خريطة عسير'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='parks_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url], verbose_name='رابط الحدائق في خريطة عسير'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='restaurants_map_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url], verbose_name='رابط المطاعم في خريطة عسير'),
        ),
    ]
