# Generated by Django 6.0.6 on 2026-06-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('core', '0004_alter_generalsettings_events_map_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feature_flags', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_settings', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='homeconfig',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_configs', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='homequickbutton',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_home_buttons', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='smartentryconfig',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smart_entry_configs', to='campaigns.campaign'),
        ),
    ]
