# Generated by Django 6.0.6 on 2026-06-29 18:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF'), ('card', 'بطاقة'), ('post', 'مقال'), ('link', 'رابط')], default='pdf', max_length=20)),
                ('summary', models.TextField()),
                ('category', models.CharField(default='توعية', max_length=80)),
                ('action_label', models.CharField(default='عرض', max_length=80)),
                ('file_url', models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url])),
                ('thumbnail_url', models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url])),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محتوى تحميل',
                'verbose_name_plural': 'مكتبة التحميلات',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AwarenessMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('text', models.TextField()),
                ('category', models.CharField(default='نصيحة', max_length=80)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رسالة توعوية',
                'verbose_name_plural': 'الرسائل التوعوية',
                'ordering': ['order', 'id'],
            },
        ),
    ]
