# Generated by Django 6.0.6 on 2026-06-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awarenesscontent',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='awareness/files/', verbose_name='رفع ملف من الجهاز'),
        ),
        migrations.AddField(
            model_name='awarenesscontent',
            name='thumbnail_upload',
            field=models.ImageField(blank=True, null=True, upload_to='awareness/thumbnails/', verbose_name='رفع صورة مصغرة'),
        ),
    ]
