# Generated by Django 6.0.6 on 2026-06-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0002_add_file_upload_fields'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awarenesscontent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awareness_contents', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='awarenessmessage',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awareness_messages', to='campaigns.campaign'),
        ),
    ]
