# Generated by Django 6.0.6 on 2026-06-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourneySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('current_location', models.CharField(max_length=80)),
                ('age_group', models.CharField(max_length=30)),
                ('party_type', models.CharField(max_length=30)),
                ('visit_purpose', models.CharField(max_length=40)),
                ('has_health_condition', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إجابة رحلة',
                'verbose_name_plural': 'إجابات الرحلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
