from .services import get_active_campaign


class ActiveCampaignAdminMixin:
    FIELD_LABELS = {
        'campaign': 'الحملة',
        'name': 'الاسم',
        'slug': 'المعرّف',
        'description': 'الوصف',
        'category': 'التصنيف',
        'city': 'المدينة',
        'target_url': 'الرابط المستهدف',
        'related_location': 'الموقع المرتبط',
        'scans_count': 'عدد المسحات',
        'last_scan_at': 'آخر مسح',
        'active': 'نشط',
        'created_at': 'تاريخ الإنشاء',
        'updated_at': 'آخر تحديث',
        'title': 'العنوان',
        'summary': 'الملخص',
        'text': 'النص',
        'question': 'السؤال',
        'answer': 'الإجابة',
        'keywords': 'الكلمات المفتاحية',
        'order': 'الترتيب',
        'status': 'الحالة',
        'is_active': 'الحملة النشطة',
        'archived_at': 'تاريخ الأرشفة',
        'logo': 'الشعار',
        'logo_static_path': 'مسار الشعار الثابت',
        'splash_image': 'صورة السبلاش',
        'splash_static_path': 'مسار صورة السبلاش الثابت',
        'background_image': 'صورة الخلفية',
        'background_static_path': 'مسار الخلفية الثابت',
        'primary_color': 'اللون الأساسي',
        'secondary_color': 'اللون الثانوي',
        'accent_color': 'لون التمييز',
        'color_settings': 'إعدادات الألوان',
        'main_title': 'العنوان الرئيسي',
        'main_description': 'الوصف الرئيسي',
        'welcome_text': 'نص الترحيب',
        'doctor_settings': 'إعدادات الدكتور مساعد',
        'qr_settings': 'إعدادات QR',
        'deep_link_settings': 'إعدادات الروابط العميقة',
        'page_settings': 'إعدادات الصفحات',
        'key': 'المفتاح',
        'banner': 'البانر',
        'banner_static_path': 'مسار البانر الثابت',
        'content': 'المحتوى',
        'settings': 'الإعدادات',
        'label': 'التسمية',
        'icon': 'الأيقونة',
        'color': 'اللون',
        'action_type': 'نوع الإجراء',
        'target_page': 'الصفحة المستهدفة',
        'url': 'الرابط',
        'deep_link': 'الرابط العميق',
        'content_type': 'نوع المحتوى',
        'action_label': 'نص الزر',
        'file_url': 'رابط الملف',
        'thumbnail_url': 'رابط الصورة المصغرة',
        'file_upload': 'رفع ملف من الجهاز',
        'thumbnail_upload': 'رفع صورة مصغرة',
        'download_count': 'عدد التحميلات',
        'link_label': 'نص الرابط',
        'link_url': 'رابط إضافي',
        'cta_label': 'نص زر الإجراء',
        'cta_url': 'رابط زر الإجراء',
        'usage_count': 'عدد الاستخدام',
        'last_used_at': 'آخر استخدام',
        'platform_name': 'اسم المنصة',
        'tagline': 'الشعار النصي',
        'intro': 'المقدمة',
        'seasonal_alert': 'تنبيه موسمي',
        'primary_button_label': 'نص الزر الرئيسي',
        'call937_label': 'نص زر 937',
        'emergency997_label': 'نص زر 997',
        'hero_image': 'صورة الواجهة',
        'enabled': 'مفعلة',
        'site_name': 'اسم الموقع',
        'default_city': 'المدينة الافتراضية',
        'support_phone': 'رقم الاستشارة',
        'emergency_phone': 'رقم الطوارئ',
        'achievement_stamp_target': 'عدد الأختام المطلوب',
        'maintenance_mode': 'وضع الصيانة',
        'offline_message': 'رسالة التوقف',
        'privacy_note': 'تنبيه الخصوصية',
        'config': 'الإعدادات',
        'location': 'الموقع',
        'date': 'التاريخ',
        'time': 'الوقت',
        'activity_type': 'نوع النشاط',
        'audience': 'الفئة المستهدفة',
        'map_url': 'رابط الخريطة',
        'show_on_home': 'عرض في الرئيسية',
        'visits': 'الزيارات',
        'location_type': 'نوع الموقع',
        'address': 'العنوان',
        'distance_label': 'المسافة',
        'availability': 'التوفر',
        'phone': 'الجوال',
        'points': 'النقاط',
        'code': 'الكود',
        'badge_label': 'وسام الشهادة',
        'required_points': 'النقاط المطلوبة',
        'required_stamps': 'الأختام المطلوبة',
        'current_location': 'الوجهة الحالية',
        'age_group': 'الفئة العمرية',
        'party_type': 'نوع الزيارة',
        'visit_purpose': 'الغرض من الزيارة',
        'has_health_condition': 'لديه حالة صحية',
        'options': 'الخيارات',
        'correct_index': 'رقم الإجابة الصحيحة',
        'result_message': 'رسالة النتيجة',
        'tip': 'النصيحة',
        'participant_name': 'اسم المشارك',
        'score': 'النتيجة',
        'total': 'الإجمالي',
        'answers': 'الإجابات',
        'item_type': 'نوع العنصر',
        'stamp': 'الختم',
        'visitor_id': 'معرف الزائر',
        'qr_type': 'نوع QR',
        'path': 'المسار',
        'qr_location': 'منطقة QR',
        'qr_item': 'عنصر QR',
        'user_agent': 'بيانات المتصفح',
        'visitor_type': 'نوع الزائر',
        'health_topic': 'الموضوع الصحي',
        'event_type': 'نوع التفاعل',
        'metadata': 'بيانات إضافية',
        'user': 'المستخدم',
        'action': 'الإجراء',
        'detail': 'التفاصيل',
        'ip_address': 'عنوان IP',
    }

    def formfield_for_dbfield(self, db_field, request, **kwargs):
        formfield = super().formfield_for_dbfield(db_field, request, **kwargs)
        if formfield and db_field.name in self.FIELD_LABELS:
            formfield.label = self.FIELD_LABELS[db_field.name]
        return formfield

    def save_model(self, request, obj, form, change):
        if hasattr(obj, 'campaign_id') and not obj.campaign_id:
            obj.campaign = get_active_campaign()
        super().save_model(request, obj, form, change)
