# Generated by Django 6.0.6 on 2026-06-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassportAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField()),
                ('badge_label', models.CharField(max_length=80)),
                ('required_points', models.PositiveIntegerField(default=0)),
                ('required_stamps', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إنجاز جواز',
                'verbose_name_plural': 'إنجازات الجواز',
                'ordering': ['required_points', 'required_stamps', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PassportStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('points', models.PositiveIntegerField(default=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ختم جواز',
                'verbose_name_plural': 'أختام الجواز',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitorPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=64, unique=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('scans_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievements', models.ManyToManyField(blank=True, related_name='passports', to='passport.passportachievement')),
                ('stamps', models.ManyToManyField(blank=True, related_name='passports', to='passport.passportstamp')),
            ],
            options={
                'verbose_name': 'جواز زائر',
                'verbose_name_plural': 'جوازات الزوار',
                'ordering': ['-updated_at'],
            },
        ),
    ]
