# Generated by Django 6.0.6 on 2026-06-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportachievement',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passport_achievements', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='passportstamp',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passport_stamps', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='visitorpassport',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitor_passports', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='passportachievement',
            name='code',
            field=models.SlugField(max_length=80),
        ),
        migrations.AlterField(
            model_name='passportstamp',
            name='slug',
            field=models.SlugField(max_length=80),
        ),
        migrations.AlterField(
            model_name='visitorpassport',
            name='visitor_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='passportachievement',
            unique_together={('campaign', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='passportstamp',
            unique_together={('campaign', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='visitorpassport',
            unique_together={('campaign', 'visitor_id')},
        ),
    ]
