# Generated by Django 6.0.6 on 2026-06-30 18:26

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='campaigns/logos/')),
                ('logo_static_path', models.CharField(blank=True, default='', max_length=220)),
                ('splash_image', models.ImageField(blank=True, null=True, upload_to='campaigns/splash/')),
                ('splash_static_path', models.CharField(blank=True, default='', max_length=220)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='campaigns/backgrounds/')),
                ('background_static_path', models.CharField(blank=True, default='', max_length=220)),
                ('primary_color', models.CharField(default='#15508A', max_length=20)),
                ('secondary_color', models.CharField(default='#283A83', max_length=20)),
                ('accent_color', models.CharField(default='#D4AF37', max_length=20)),
                ('color_settings', models.JSONField(blank=True, default=dict)),
                ('main_title', models.CharField(blank=True, max_length=180)),
                ('main_description', models.TextField(blank=True)),
                ('welcome_text', models.CharField(blank=True, max_length=220)),
                ('doctor_settings', models.JSONField(blank=True, default=dict)),
                ('qr_settings', models.JSONField(blank=True, default=dict)),
                ('deep_link_settings', models.JSONField(blank=True, default=dict)),
                ('page_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaign Management',
                'ordering': ['-is_active', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='campaign_single_active_true')],
            },
        ),
        migrations.CreateModel(
            name='CampaignInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('visit', 'Visitor'), ('qr_scan', 'QR Scan'), ('assistant_open', 'Doctor Assistant Open'), ('assistant_query', 'Doctor Assistant Query'), ('interaction', 'Interaction')], db_index=True, max_length=30)),
                ('visitor_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('path', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Interaction',
                'verbose_name_plural': 'Campaign Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='campaigns/pages/')),
                ('banner_static_path', models.CharField(blank=True, default='', max_length=220)),
                ('content', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Page',
                'verbose_name_plural': 'Campaign Pages',
                'ordering': ['order', 'key'],
                'unique_together': {('campaign', 'key')},
            },
        ),
        migrations.CreateModel(
            name='CampaignButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=90)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('action_type', models.CharField(choices=[('page', 'Open page'), ('deep_link', 'Open Deep Link'), ('external', 'Open external link'), ('assistant', 'Open Doctor Assistant')], default='page', max_length=20)),
                ('url', models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url])),
                ('deep_link', models.CharField(blank=True, max_length=240)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='campaigns.campaign')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='campaigns.campaignpage')),
                ('target_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_buttons', to='campaigns.campaignpage')),
            ],
            options={
                'verbose_name': 'Campaign Button',
                'verbose_name_plural': 'Campaign Buttons',
                'ordering': ['order', 'id'],
            },
        ),
    ]
