# Generated by Django 6.0.6 on 2026-06-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_seed_summer_health_campaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'حملة', 'verbose_name_plural': 'إدارة الحملات'},
        ),
        migrations.AlterModelOptions(
            name='campaignbutton',
            options={'ordering': ['order', 'id'], 'verbose_name': 'زر حملة', 'verbose_name_plural': 'أزرار الحملات'},
        ),
        migrations.AlterModelOptions(
            name='campaigninteraction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تفاعل حملة', 'verbose_name_plural': 'تفاعلات الحملات'},
        ),
        migrations.AlterModelOptions(
            name='campaignpage',
            options={'ordering': ['order', 'key'], 'verbose_name': 'صفحة حملة', 'verbose_name_plural': 'صفحات الحملات'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('disabled', 'معطلة'), ('archived', 'مؤرشفة')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignbutton',
            name='action_type',
            field=models.CharField(choices=[('page', 'فتح صفحة'), ('deep_link', 'فتح رابط عميق'), ('external', 'فتح رابط خارجي'), ('assistant', 'فتح الدكتور مساعد')], default='page', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaigninteraction',
            name='event_type',
            field=models.CharField(choices=[('visit', 'زائر'), ('qr_scan', 'مسح QR'), ('assistant_open', 'فتح الدكتور مساعد'), ('assistant_query', 'سؤال الدكتور مساعد'), ('interaction', 'تفاعل')], db_index=True, max_length=30),
        ),
    ]
