# Generated by Django 6.0.6 on 2026-06-29 18:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAssistantQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=180)),
                ('answer', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سؤال الدكتور مساعد',
                'verbose_name_plural': 'أسئلة الدكتور مساعد',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='KeywordAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=180)),
                ('keywords', models.JSONField(default=list)),
                ('answer', models.TextField()),
                ('link_label', models.CharField(blank=True, max_length=80)),
                ('link_url', models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url])),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url])),
                ('active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'كلمة مفتاحية وإجابة',
                'verbose_name_plural': 'الكلمات المفتاحية والإجابات',
                'ordering': ['question'],
            },
        ),
    ]
