# Generated by Codex on 2026-06-30

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorassistantquestion',
            name='cta_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='doctorassistantquestion',
            name='cta_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url]),
        ),
        migrations.AddField(
            model_name='doctorassistantquestion',
            name='link_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='doctorassistantquestion',
            name='link_url',
            field=models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url]),
        ),
    ]
