# Generated by Django 6.0.6 on 2026-06-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_doctorassistantquestion_links'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorassistantquestion',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_questions', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='keywordanswer',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keyword_answers', to='campaigns.campaign'),
        ),
    ]
