# Generated by Django 6.0.6 on 2026-06-29 18:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('location_type', models.CharField(choices=[('health_center', 'مركز صحي'), ('hospital', 'مستشفى'), ('pharmacy', 'صيدلية'), ('walkway', 'ممشى'), ('awareness', 'نقطة توعوية'), ('emergency', 'طوارئ')], default='health_center', max_length=30)),
                ('city', models.CharField(default='أبها', max_length=80)),
                ('address', models.CharField(blank=True, max_length=220)),
                ('distance_label', models.CharField(blank=True, max_length=60)),
                ('availability', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('map_url', models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url])),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'موقع صحي ومهم',
                'verbose_name_plural': 'المواقع الصحية والمهمة',
                'ordering': ['order', 'city', 'name'],
            },
        ),
    ]
