# Generated by Django 6.0.6 on 2026-06-29 18:24

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('item_type', models.CharField(default='عنصر', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('target_url', models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url])),
                ('scans_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stamp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_items', to='passport.passportstamp')),
            ],
            options={
                'verbose_name': 'عنصر QR',
                'verbose_name_plural': 'عناصر QR',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QrLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='موقع', max_length=80)),
                ('city', models.CharField(default='أبها', max_length=80)),
                ('target_url', models.CharField(blank=True, max_length=240, validators=[core.validators.validate_safe_url])),
                ('scans_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_locations', to='locations.healthlocation')),
            ],
            options={
                'verbose_name': 'موقع QR',
                'verbose_name_plural': 'مواقع QR',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QrLocationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='qr.qrlocation')),
            ],
            options={
                'verbose_name': 'زيارة موقع QR',
                'verbose_name_plural': 'زيارات مواقع QR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QrScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('qr_type', models.CharField(choices=[('location', 'موقع'), ('item', 'عنصر')], max_length=20)),
                ('path', models.CharField(max_length=240)),
                ('user_agent', models.CharField(blank=True, max_length=260)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qr.qritem')),
                ('qr_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qr.qrlocation')),
            ],
            options={
                'verbose_name': 'مسح QR',
                'verbose_name_plural': 'مسوحات QR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QrVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='qr.qritem')),
            ],
            options={
                'verbose_name': 'زيارة عنصر QR',
                'verbose_name_plural': 'زيارات عناصر QR',
                'ordering': ['-created_at'],
            },
        ),
    ]
