# Generated by Django 5.2.5 on 2026-06-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrlocation',
            name='last_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QrVisitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=64, unique=True)),
                ('visitor_type', models.CharField(blank=True, choices=[('visitor', 'زائر'), ('resident', 'مقيم')], max_length=20)),
                ('party_type', models.CharField(blank=True, choices=[('individual', 'فرد'), ('family', 'عائلة')], max_length=20)),
                ('age_group', models.CharField(blank=True, choices=[('under_18', 'أقل من 18'), ('18_30', '18-30'), ('31_50', '31-50'), ('51_plus', '51+')], max_length=20)),
                ('health_topic', models.CharField(blank=True, choices=[('blood_pressure', 'ضغط الدم'), ('diabetes', 'السكري'), ('heart_health', 'صحة القلب'), ('nutrition', 'التغذية'), ('physical_activity', 'النشاط البدني'), ('walking', 'المشي'), ('elderly', 'كبار السن'), ('sleep', 'النوم'), ('sun_protection', 'الوقاية من الشمس')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_profiles', to='qr.qrlocation')),
            ],
            options={
                'verbose_name': 'إحصائية زائر QR',
                'verbose_name_plural': 'إحصائيات زوار QR',
                'ordering': ['-updated_at'],
            },
        ),
    ]
