# Generated by Django 5.2.5 on 2026-06-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_qrlocation_last_scan_at_qrvisitorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrlocation',
            name='last_scan_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مسح'),
        ),
    ]
