# Generated by Django 6.0.6 on 2026-06-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('qr', '0003_alter_qrlocation_last_scan_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qritem',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_items', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_locations', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='qrlocationvisit',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_location_visits', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_scans', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='qrvisit',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_item_visits', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='qrvisitorprofile',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_visitor_profiles', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='qrlocation',
            name='slug',
            field=models.SlugField(max_length=90),
        ),
        migrations.AlterField(
            model_name='qrvisitorprofile',
            name='visitor_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='qrlocation',
            unique_together={('campaign', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='qrvisitorprofile',
            unique_together={('campaign', 'visitor_id')},
        ),
    ]
