# Generated by Django 6.0.6 on 2026-06-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthHeroEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('badge_label', models.CharField(max_length=120)),
                ('answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مشاركة تحدي',
                'verbose_name_plural': 'المشاركون في تحدي بطل الصحة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthHeroQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.PositiveIntegerField(default=0)),
                ('result_message', models.CharField(max_length=180)),
                ('tip', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سؤال تحدي بطل الصحة',
                'verbose_name_plural': 'أسئلة تحدي بطل الصحة',
                'ordering': ['order', 'id'],
            },
        ),
    ]
