# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthheroentry',
            name='participant_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='healthheroentry',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
