# Generated by Django 6.0.6 on 2026-06-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('hero', '0002_healthheroentry_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthheroentry',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero_entries', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='healthheroquestion',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero_questions', to='campaigns.campaign'),
        ),
    ]
